language: android
dist: trusty

# android:
#   components:
#     - build-tools-28.0.3
#     - android-28
#   licenses:
#     - "android-sdk-preview-license-52d11cd2"
#     - "android-sdk-license-.+"
#     - "google-gdk-license-.+"

os: osx
osx_image: xcode11.3

install:
  - ./.travis/install.sh

script:
  - ./.travis/analyze.sh
